### ISSUE TITLE
Add information about licensing

### ISSUE THREAD

**Issue by vbauer** [lisawray/passwordview#1]

**Comment by tir38** [comment]
Srsly. I want to use this in a legit project.

**Comment by markcerqueira** [comment]
Great project and would love to use it for the @evernote app. Could you add a license?

**Comment by lisawray** [comment]
So sorry!  My notifications from github were messed up and I didn't get any of these!!  I've just added the most permissive license I can find and will be going through the rest of the pull requests/ issues tonight.

**Comment by vbauer** [comment]
Thank you for information!
