### ISSUE TITLE
clicked coordinate calculation error of eye icon

### ISSUE THREAD

**Issue by nickwongwong** [lisawray/passwordview#11]
When we use "padding" or "center_horizontal" of PasswordView, `(getRight() - getCompoundDrawables()[2].getBounds().width())` will not show the true location of eye icon.
In this way, `onTouchEvent` can not handle the click event correctly.
Using `getWidth()` instead of `getRight()`, and `getPaddingRight()`

**Comment by behelit** [comment]
Having the same issue. If I use padding, the user can only toggle it by tapping the very end of the edit text field (i.e the last pixel)
Same results when using padding on either the TextInputLayout or directly on the PasswordView

**Comment by lisawray** [comment]
Fixed! https://github.com/lisawray/passwordview/pull/18
