### ISSUE TITLE
The non highlighted underline remains visible when PasswordView is highlighted.

### ISSUE THREAD

**Issue by jpardogo** [lisawray/passwordview#2]
First of all, nice library. I just noticed one little thing.
The non highlighted underline remains visible when `PasswordView` is highlighted.
Device: Samsung Galaxy S4, Android 5.0.1.
Hope it helps.
![device-2016-03-16-153619](https://cloud.githubusercontent.com/assets/1172221/13819090/2a40a898-eb90-11e5-8458-26676bf74e03.png)
![device-2016-03-16-153631](https://cloud.githubusercontent.com/assets/1172221/13819089/2a3ace78-eb90-11e5-8a0a-63ecc3642a58.png)

**Comment by lisawray** [comment]
I don't have an S4 at the moment, but I think this has got to be a bug with _any_ EditText, not just this one!  Leaving open for now to see if I can get my hands on one.

**Comment by jpardogo** [comment]
Library deprecated so I close the issue
