### ISSUE TITLE
Using setError invalidates the eye toggle

### ISSUE THREAD

**Issue by powder366** [lisawray/passwordview#5]
When using setError on the EditText the eye toggle stops working and does not toggle the drawable itself (the shown/hidden text works). I assume it resets the drawable somehow, any idea how to fix it?

**Comment by lisawray** [comment]
Forgot a TextView could even do this! 

Do you think it makes sense for it to work like it currently does -- replacing the eye while the error is shown -- or should the eye be visible also?

**Comment by andhie** [comment]
The Material guidelines [Components– Text fields](https://material.google.com/components/text-fields.html#) doesn't use the existing [TextView#setError](https://developer.android.com/reference/android/widget/TextView.html#setError%28java.lang.CharSequence%29) method anymore. Yet it is also unclear if its "deprecated" in favor of [TextInputLayout#setError](https://developer.android.com/reference/android/support/design/widget/TextInputLayout.html#setError%28java.lang.CharSequence%29)

**Comment by powder366** [comment]
I switched to android.support.design.widget.TextInputLayout, here the error is displayed underneath.

**Comment by lisawray** [comment]
I like your method @powder366. :) I'll just disable it.  It really doesn't make sense to use TextView.setError with the eye toggle.

**Comment by lisawray** [comment]
https://github.com/lisawray/passwordview/pull/26
